"""Initial

Revision ID: 85395fa29bdc
Revises: 
Create Date: 2025-08-07 14:51:20.871744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85395fa29bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_complaint_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notifications_suggestion_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'complaints', ['complaint_id'], ['complaint_id'])
        batch_op.create_foreign_key(None, 'suggestions', ['suggestion_id'], ['suggestion_id'])

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column('suggestion_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('reviewed', 'unreviewed', name='suggestionstatus'),
               nullable=False,
               existing_server_default=sa.text("'unreviewed'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column('suggestion_status',
               existing_type=sa.Enum('reviewed', 'unreviewed', name='suggestionstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unreviewed'::character varying"))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_suggestion_id_fkey'), 'suggestions', ['suggestion_id'], ['suggestion_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('notifications_complaint_id_fkey'), 'complaints', ['complaint_id'], ['complaint_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
